apiVersion: v1
kind: Pod
metadata:
  name: tester-pod
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: test-script-volume
      mountPath: /test
  volumes:
  - name: test-script-volume
    configMap:
      name: tester-config
  restartPolicy: Never